# Generated by Django 5.0.4 on 2024-05-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='update',
            new_name='updated',
        ),
    ]
